In [2]:
!ls
#collecting data from hosting sites

linkedin data analysis job listing.ipynb
linkedin-jobs-africa.csv

In [3]:
#import thee library
import pandas as pd

In [4]:
data_jobs = pd.read_csv('linkedin-jobs-africa.csv') #reading a dataset to a df

In [5]:
type(data_jobs)

pandas.core.frame.DataFrame

In [6]:
data_jobs.head()

,title,company,description,onsite_remote,salary,location,criteria,posted_date,link
0,Data Analyst,NNC,We are looking for a passionate certified Data...,onsite,NaN,"Cairo, Cairo, Egypt","[{'مستوى الأقدمية': 'غير مطبق'}, {'نوع التوظيف...",2022-11-18,https://eg.linkedin.com/jobs/view/data-analyst...
1,Data Analyst,Watu Credit,"WATU is a focus-driven, customer-centric compa...",onsite,NaN,"Nairobi County, Kenya","[{'Seniority level': 'Associate'}, {'Employmen...",2022-11-01,https://ke.linkedin.com/jobs/view/data-analyst...
2,Data Analyst (Credit Risk),Kuda,Kuda is a fintech on a mission to make financi...,onsite,NaN,"Cape Town, Western Cape, South Africa","[{'Seniority level': 'Not Applicable'}, {'Empl...",2022-11-21,https://za.linkedin.com/jobs/view/data-analyst...
3,Data Analyst,Watu Credit,Role: Data AnalystReporting to: Data Analytics...,onsite,NaN,"Nairobi, Nairobi County, Kenya","[{'Seniority level': 'Mid-Senior level'}, {'Em...",2022-11-01,https://ke.linkedin.com/jobs/view/data-analyst...
4,Data Analyst,Tata Consultancy Services,About Tata Consultancy ServicesTata Consultanc...,onsite,NaN,"City of Johannesburg, Gauteng, South Africa","[{'Seniority level': 'Mid-Senior level'}, {'Em...",2022-10-27,https://za.linkedin.com/jobs/view/data-analyst...

In [7]:
## obtaining data from api

In [8]:
#import librariex
import requests
import json

In [9]:
api_key = "AIzaSyCuKvLNjyPuSmmiQZlWm-hcCBpCUTJe31k"

In [10]:
search_url = "https://maps.googleapis.com/maps/api/place/textsearch/json?"

In [11]:
query = 'TalentQL'

In [12]:
response = requests.get(search_url + 'query=' +query+'&key='+api_key)
json_object = response.json()

In [13]:
json_object

{'html_attributions': [],
 'results': [{'business_status': 'OPERATIONAL',
   'formatted_address': '9 Professor Gabriel Olusanya St, Lekki Phase 1, Lagos 106104, Lagos, Nigeria',
   'geometry': {'location': {'lat': 6.4306491, 'lng': 3.4779887},
    'viewport': {'northeast': {'lat': 6.432002229892722,
      'lng': 3.479413129892722},
     'southwest': {'lat': 6.429302570107278, 'lng': 3.476713470107278}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
   'icon_background_color': '#7B9EB0',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet',
   'name': 'TalentQL',
   'opening_hours': {},
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111559470809565460582">mercy ikpe</a>'],
     'photo_reference': 'AcnlKN0TxdKOWPC1JTKVlo_vWcz6D66nTVaMU7N-jg5lmOQV6iXNCNcbHQVcFqmh5qORZAII6pXsMHroOrzgkx8PjwqZh7FRZLPfeAqwz_iXFiyT0GvbSAB7dBzy21aQ9U2ohbjPGMKw_nChnhnYvXhJfGWjOW7q-Gi5jW1_uGYJdfNFybyVsp2oJybtVpaiInNBjOzE7HK1duHXH3wRrKMBVAU-CmPVXgQzNqWaLHvgIng-INJOu3F7zuoIsYfUxUNVlV0h2OTIEC3Bw1Rmcs1Do7WStkx3fnN_0RMPvLgKSwjDPoP3JOpNT2i_-8vYACa7f1Ly0OnqRu7YYEGhE7d4u84_0hpinyzgPXAPu3LK02EsIiCHl5Pht6RzeRqzcwQ2fQeRtTdGwiM0-AmDzZ6JZv2R-ykgJE40Abk-c0meHOdpx2tKNb3HPh_Ou2otvRLmRiGjvw8FuNtlfOpK1OYhJlGOjVJIJEiLF7BIHuSnzlwvCMUSO8o9WYp3ugkoewn9XO8GLSDuV-Glcw8H8RmGdIRtE3L2LKC8llbRJFyTypv4b7IoQvsRPaZoUa7N4vfKcICdrWmXXXhAVg',
     'width': 3024}],
   'place_id': 'ChIJ1y8O8qD1OxARRb_DOvYIyq4',
   'rating': 4.8,
   'reference': 'ChIJ1y8O8qD1OxARRb_DOvYIyq4',
   'types': ['point_of_interest', 'establishment'],
   'user_ratings_total': 30}],
 'status': 'OK'}

In [14]:
#print address and name of location
print(json_object['results'][0]['formatted_address'])
print(json_object['results'][0]['name'])

9 Professor Gabriel Olusanya St, Lekki Phase 1, Lagos 106104, Lagos, Nigeria
TalentQL

In [15]:
## this is how wwe get informations using APIs. 
# Data can be obtained by making API requests to organizations that have data in their private repositories. the data can be obtained by the following steps

## introduction to pandas

pandas.. is a model, a package that helps define the kind of problems we are trying to solve. it's a python library used  for analyzing, transforming, cleaning, manipulating and wrangling statistics from data. it can be used to generate statistics from data
why?
easy to use and learn
open source
built in fxn for exploratory data analysis
built in support for various data structures and format.

two data structure
series and data frames
series is a one dimentional data structure think of it as a colunm in a single excel sheet while data frames is a two dimensional date structure. it has a row and it has a column, and in it's intersection is the value of a data.

In [16]:
## hands on session w pandas

In [17]:
import pandas as pd
#imported the pandas module

In [18]:
url_link = "https://en.wikipedia.org/wiki/list_of_highest-grossing_flims"

In [19]:
# Source - https://stackoverflow.com/a
# Posted by ghareeb fathy
# Retrieved 2025-12-02, License - CC BY-SA 4.0

import ssl

ssl._create_default_https_context = ssl._create_stdlib_context

In [20]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [21]:
import pandas as pd

url_link = "/Users/mac/Downloads/List of highest-grossing films - Wikipedia.html"
movie_data = pd.read_html(url_link)

type(movie_data)

list

movie_data = movie_data[0]

In [22]:
type(movie_data)

list

In [23]:
import pandas as pd

In [24]:
url_link = "/Users/mac/Downloads/List of highest-grossing films - Wikipedia.html"

In [25]:
movie_data = movie_data[0]

In [26]:
type(movie_data)

pandas.core.frame.DataFrame

In [27]:
## a dataframe holds rows and columns. an intersection of a row and columns holds data values

In [28]:
movie_data.head()

   Rank Peak                     Title  Worldwide gross  Year          Ref
0     1    1                    Avatar   $2,923,710,708  2009   [# 1][# 2]
1     2    1         Avengers: Endgame   $2,797,501,328  2019   [# 3][# 4]
2     3    3  Avatar: The Way of Water   $2,343,096,253  2022   [# 5][# 6]
3     4    1                   Titanic  T$2,257,906,828  1997   [# 7][# 8]
4     5    5                  Ne Zha 2   $2,215,690,000  2025  [# 9][# 10]

In [29]:
## series is basically a one dimentional data. it simply has rows numbbers on one side, which are the index that comes with the data amd just one column

In [30]:
movie_data['Title'].head()

0                      Avatar
1           Avengers: Endgame
2    Avatar: The Way of Water
3                     Titanic
4                    Ne Zha 2
Name: Title, dtype: object

In [31]:
movie_data_s = movie_data ['Title'].head()

In [32]:
type(movie_data-_)

pandas.core.frame.DataFrame

In [33]:
## DEFRAMING DATA

In [34]:
movie_data.head(10)
## the head function is designed to print out the first five rows but we called out 10 that's why we have 10 here

,Rank,Peak,Title,Worldwide gross,Year,Ref
0,1,1,Avatar,"$2,923,710,708",2009,[# 1][# 2]
1,2,1,Avengers: Endgame,"$2,797,501,328",2019,[# 3][# 4]
2,3,3,Avatar: The Way of Water,"$2,343,096,253",2022,[# 5][# 6]
3,4,1,Titanic,"T$2,257,906,828",1997,[# 7][# 8]
4,5,5,Ne Zha 2,"$2,215,690,000",2025,[# 9][# 10]
5,6,3,Star Wars: The Force Awakens,"$2,068,223,624",2015,[# 11][# 12]
6,7,4,Avengers: Infinity War,"$2,048,359,754",2018,[# 13][# 14]
7,8,6,Spider-Man: No Way Home,"SM$1,922,598,800",2021,[# 15][# 16]
8,9,8,Inside Out 2,"$1,698,863,816",2024,[# 17][# 18]
9,10,3,Jurassic World,"$1,671,537,444",2015,[# 19][# 20]

In [35]:
movie_data.tail()
# this prints out the last 5 rows

,Rank,Peak,Title,Worldwide gross,Year,Ref
45,46,34,Aladdin,"$1,050,693,953",2019,[# 79][# 4]
46,47,2,Star Wars: Episode I – The Phantom Menace,"$1,046,515,409",1999,[# 80][# 8]
47,48,6,Pirates of the Caribbean: On Stranger Tides,"$1,045,713,802",2011,[# 81][# 72]
48,49,49,Lilo & Stitch †,"$1,037,971,167",2025,[# 82][# 83]
49,50,1,Jurassic Park,"$1,037,535,230",1993,[# 84][# 85]

In [36]:
movie_data.tail(10) 
##here we added 10 that's why we're getting the last 10 rows

,Rank,Peak,Title,Worldwide gross,Year,Ref
40,41,30,Toy Story 4,"$1,073,394,593",2019,[# 70][# 4]
41,42,4TS3,Toy Story 3,"$1,066,970,811",2010,[# 71][# 72]
42,43,3,Pirates of the Caribbean: Dead Man's Chest,"$1,066,179,747",2006,[# 73][# 74]
43,44,44,Moana 2,"$1,059,242,164",2024,[# 75][# 76]
44,45,20,Rogue One: A Star Wars Story,"$1,057,420,387",2016,[# 77][# 78]
45,46,34,Aladdin,"$1,050,693,953",2019,[# 79][# 4]
46,47,2,Star Wars: Episode I – The Phantom Menace,"$1,046,515,409",1999,[# 80][# 8]
47,48,6,Pirates of the Caribbean: On Stranger Tides,"$1,045,713,802",2011,[# 81][# 72]
48,49,49,Lilo & Stitch †,"$1,037,971,167",2025,[# 82][# 83]
49,50,1,Jurassic Park,"$1,037,535,230",1993,[# 84][# 85]

In [37]:
## let's index this dataframe
## when we use [] that makes it possible to look at what we have and decide what we are indexing our colunm by

In [38]:
movie_data.columns

Index(['Rank', 'Peak', 'Title', 'Worldwide gross', 'Year', 'Ref'], dtype='object')

In [39]:
movie_data['Rank']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
35    36
36    37
37    38
38    39
39    40
40    41
41    42
42    43
43    44
44    45
45    46
46    47
47    48
48    49
49    50
Name: Rank, dtype: int64

In [40]:
movie_data['Rank'].head()
## here we're just trying to see the first five

0    1
1    2
2    3
3    4
4    5
Name: Rank, dtype: int64

In [41]:
## hands on googlesearch engines
## creating dataframes using lists

In [42]:
lst_names = ['yomi', 'miriam', 'Esther', 'martina']

In [43]:
names=pd.DataFrame(data=lst_names, columns= [ 'Names'])

In [44]:
type(names)

pandas.core.frame.DataFrame

In [45]:
names

     Names
0     yomi
1   miriam
2   Esther
3  martina

In [46]:
## creating lists with dict

student_data = {
    'name': ['Jack', 'Rita', 'Aadi', 'New york'],
    'age': [34, 30, 16, 20],
    'city': ['sydney', 'Delhi', 'New york', 'Paris']
}

In [47]:
names_data= pd.DataFrame(data= student_data, columns=['names', 'age',  'city'])

In [48]:
names_data

  names  age      city
0   NaN   34    sydney
1   NaN   30     Delhi
2   NaN   16  New york
3   NaN   20     Paris

In [49]:
## retriving data using columns or sequence

names_data.loc[1]

names      NaN
age         30
city     Delhi
Name: 1, dtype: object

In [50]:
# or you use the iloc

names_data.iloc[1]

names      NaN
age         30
city     Delhi
Name: 1, dtype: object

In [51]:
# data types
names_data.dtypes

names    object
age       int64
city     object
dtype: object

In [52]:
## nan fix



student_data = {
    'name': ['Jack', 'Rita', 'Aadi', 'New york'],
    'age': [34, 30, 16, 20],
    'city': ['sydney', 'Delhi', 'New york', 'Paris']
}

names_data = pd.DataFrame(student_data)

print(names_data.head())

       name  age      city
0      Jack   34    sydney
1      Rita   30     Delhi
2      Aadi   16  New york
3  New york   20     Paris

In [53]:
## inserting and deleting

names_data

       name  age      city
0      Jack   34    sydney
1      Rita   30     Delhi
2      Aadi   16  New york
3  New york   20     Paris

In [54]:
names_data.size

12

In [55]:
names_data.shape

(4, 3)

In [56]:
## insert row
## create a series first

john = pd.Series(data= ['John',28, 'Kaduna'], index = names_data.columns, name=3)

In [57]:
john

name      John
age         28
city    Kaduna
Name: 3, dtype: object

In [58]:
# add a row
pd.concat([names_data, john.to_frame().T], ignore_index=True)

       name age      city
0      Jack  34    sydney
1      Rita  30     Delhi
2      Aadi  16  New york
3  New york  20     Paris
4      John  28    Kaduna

In [59]:
names_data

       name  age      city
0      Jack   34    sydney
1      Rita   30     Delhi
2      Aadi   16  New york
3  New york   20     Paris

In [60]:
## add a column
names_data['jobs'] = ['Banker', 'Salesman', 'laborer', 'instructor']

In [61]:
names_data

       name  age      city        jobs
0      Jack   34    sydney      Banker
1      Rita   30     Delhi    Salesman
2      Aadi   16  New york     laborer
3  New york   20     Paris  instructor

In [62]:
#del columns
names_data = names_data.drop(columns=['jobs'] )

In [63]:
names_data

       name  age      city
0      Jack   34    sydney
1      Rita   30     Delhi
2      Aadi   16  New york
3  New york   20     Paris

In [64]:
names_data = names_data.drop(index=3)
print(names_data.head())

   name  age      city
0  Jack   34    sydney
1  Rita   30     Delhi
2  Aadi   16  New york

In [65]:
names_data

   name  age      city
0  Jack   34    sydney
1  Rita   30     Delhi
2  Aadi   16  New york

### to frame the data set or the data frametowards the insight you're looking for, you have to set it up for the analysis you want to do

 the concept of dirty data.
 Date science is a huge discipline concern with extracting insights from huge amount of data.
 raw data contains irregularities, inconsistencies, missing information, duplicate data, incomplete information
 business cases are the reason why we build models. they're bottomlines for organizations.

In [66]:
url_link1 = "https://en.wikipedia.org/wiki/List_of_largest_companies_by_revenue"

In [67]:
company_data = pd.read_html(
    url_link1,
    storage_options={"User-Agent": "Mozilla/5.0"}
)

In [68]:
type(company_data)

list

In [69]:
company_data = company_data[0]

In [70]:
company_data.head()

,Ranks,Name,Industry,Revenue,Profit,Employees,Headquarters[note 1],State-owned,Ref.,Unnamed: 9_level_0
,Ranks,Name,Industry,USD (in millions),USD (in millions),Employees,Headquarters[note 1],State-owned,Ref.,Unnamed: 9_level_1
0,1,Walmart,Retail,"$680,985","$19,436",2100000,United States,NaN,[1],NaN
1,2,Amazon,Retail information technology,"$637,959","$59,248",1556000,United States,NaN,[5],NaN
2,3,State Grid Corporation of China,Electricity,"$545,948","$9,204",1361423,China,NaN,[6],NaN
3,4,Saudi Aramco,Oil and gas,"$480,446","$106,246",73311,Saudi Arabia,NaN,[7],NaN
4,5,China National Petroleum Corporation,Oil and gas,"$476,000","$25,250",1026301,China,NaN,[8],NaN

In [71]:
company_data.columns

MultiIndex([(               'Ranks',                'Ranks'),
            (                'Name',                 'Name'),
            (            'Industry',             'Industry'),
            (             'Revenue',    'USD (in millions)'),
            (              'Profit',    'USD (in millions)'),
            (           'Employees',            'Employees'),
            ('Headquarters[note 1]', 'Headquarters[note 1]'),
            (         'State-owned',          'State-owned'),
            (                'Ref.',                 'Ref.'),
            (  'Unnamed: 9_level_0',   'Unnamed: 9_level_1')],
           )

In [72]:
company_data.columns = company_data.columns.get_level_values(0)

In [73]:
company_data.columns

Index(['Ranks', 'Name', 'Industry', 'Revenue', 'Profit', 'Employees',
       'Headquarters[note 1]', 'State-owned', 'Ref.', 'Unnamed: 9_level_0'],
      dtype='object')

In [74]:
company_data.head()

,Ranks,Name,Industry,Revenue,Profit,Employees,Headquarters[note 1],State-owned,Ref.,Unnamed: 9_level_0
0,1,Walmart,Retail,"$680,985","$19,436",2100000,United States,NaN,[1],NaN
1,2,Amazon,Retail information technology,"$637,959","$59,248",1556000,United States,NaN,[5],NaN
2,3,State Grid Corporation of China,Electricity,"$545,948","$9,204",1361423,China,NaN,[6],NaN
3,4,Saudi Aramco,Oil and gas,"$480,446","$106,246",73311,Saudi Arabia,NaN,[7],NaN
4,5,China National Petroleum Corporation,Oil and gas,"$476,000","$25,250",1026301,China,NaN,[8],NaN

In [75]:
## we're going to drop the ref column
company_data.drop(columns=['Ref.'], axis=1)
# thia doesn't mean we've removed the ref column, it's just showing us what it looks like without the ref columns

,Ranks,Name,Industry,Revenue,Profit,Employees,Headquarters[note 1],State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,"$680,985","$19,436",2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,"$637,959","$59,248",1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,"$545,948","$9,204",1361423,China,NaN,NaN
3,4,Saudi Aramco,Oil and gas,"$480,446","$106,246",73311,Saudi Arabia,NaN,NaN
4,5,China National Petroleum Corporation,Oil and gas,"$476,000","$25,250",1026301,China,NaN,NaN
5,6,China Petrochemical Corporation,Oil and gas,"$429,700","$9,393",513434,China,NaN,NaN
6,7,UnitedHealth Group,Healthcare,"$400,278","$14,405",400000,United States,NaN,NaN
7,8,Apple,Information technology,"$391,035","$93,736",164000,United States,NaN,NaN
8,9,Berkshire Hathaway,Financials,"$371,433","$88,995",392400,United States,NaN,NaN
9,10,CVS Health,Healthcare,"$357,776","$8,344",259500,United States,NaN,NaN
10,11,Alphabet,Information technology,"$350,018","$100,118",183323,United States,NaN,NaN
11,12,Volkswagen Group,Automotive,"$348,408","$17,945",684025,Germany,NaN,NaN
12,13,ExxonMobil,Oil and gas,"$344,582","$36,010",61500,United States,NaN,NaN
13,14,Vitol,Commodities,"$331,000","$13,000",1560,Switzerland,NaN,NaN
14,15,Shell,Oil and gas,"$323,183","$19,359",103000,United Kingdom,NaN,NaN
15,16,China State Construction Engineering,Construction,"$320,431","$4,272",382894,China,NaN,NaN
16,17,Toyota,Automotive,"$312,018","$34,214",380793,Japan,NaN,NaN
17,18,McKesson,Healthcare,"$308,951","$3,002",48000,United States,NaN,NaN
18,19,Microsoft,Information technology,"$281,700","$101,800",228000,United States,NaN,NaN
19,20,Cencora,Healthcare,"$262,173","$1,745",44000,United States,NaN,NaN
20,21,Trafigura,Commodities,"$244,280","$7,393",12479,Singapore,NaN,NaN
21,22,Costco,Retail,"$242,290","$6,292",316000,United States,NaN,NaN
22,23,JPMorgan Chase,Financials,"$239,425","$49,552",309926,United States,NaN,NaN
23,24,Industrial and Commercial Bank of China,Financials,"$222,484","$51,417",419252,China,NaN,NaN
24,25,TotalEnergies,Oil and gas,"$218,945","$21,384",102579,France,NaN,NaN
25,26,Glencore,Commodities,"$217,829","$4,280",83426,Switzerland,NaN,NaN
26,27,BP,Oil and gas,"$213,032","$15,239",79400,United Kingdom,NaN,NaN
27,28,Cardinal Health,Healthcare,"$205,012",$261,47520,United States,NaN,NaN
28,29,Stellantis,Automotive,"$204,908","$20,103",258275,Netherlands,NaN,NaN
29,30,Chevron,Oil and gas,"$200,949","$21,369",45600,United States,NaN,NaN
30,31,China Construction Bank,Financials,"$199,826","$46,990",376871,China,NaN,NaN
31,32,Samsung Electronics,Electronics,"$198,257","$11,082",267860,South Korea,NaN,NaN
32,33,Foxconn,Electronics,"$197,876","$4,563",621393,Taiwan,NaN,NaN
33,34,Cigna,Healthcare,"$195,265","$5,164",71413,United States,NaN,NaN
34,35,Agricultural Bank of China,Financials,"$192,398","$38,049",451003,China,NaN,NaN
35,36,Schwarz Gruppe,Retail,"$180,576","$16,988",595000,Germany,NaN,NaN
36,37,China Railway Engineering Corporation,Construction,"$178,563","$2,152",314149,China,NaN,NaN
37,38,Cargill,Conglomerate,"$177,000","$17,641",160000,United States,NaN,NaN
38,39,Ford Motor Company,Automotive,"$176,191","$4,347",177000,United States,NaN,NaN
39,40,Bank of China,Financials,"$172,328","$32,758",306931,China,NaN,NaN
40,41,Bank of America,Financials,"$171,912","$26,515",212985,United States,NaN,NaN
41,42,General Motors,Automotive,"$171,842","$10,127",163000,United States,NaN,NaN
42,43,Elevance Health,Healthcare,"$171,340","$5,987",104900,United States,NaN,NaN
43,44,BMW Group,Automotive,"$168,103","$12,205",154950,Germany,NaN,NaN
44,45,Mercedes-Benz Group,Automotive,"$165,638","$15,417",166056,Germany,NaN,NaN
45,46,Meta Platforms,Social media,"$164,500","$62,360",78450,United States,NaN,NaN
46,47,China Railway Construction Corporation,Construction,"$160,847","$1,701",336433,China,NaN,NaN
47,48,Baowu,Steel,"$157,216","$2,494",258697,China,NaN,NaN
48,49,Citigroup,Financials,"$156,820","$9,228",237925,United States,NaN,NaN
49,50,Nvidia,Semiconductors,"$155,500","$31,910",36000,United States,NaN,NaN
50,51,Enel,Energy,"$147,100","$3,400",61060,Italy,NaN,NaN

In [76]:
company_data.head()

,Ranks,Name,Industry,Revenue,Profit,Employees,Headquarters[note 1],State-owned,Ref.,Unnamed: 9_level_0
0,1,Walmart,Retail,"$680,985","$19,436",2100000,United States,NaN,[1],NaN
1,2,Amazon,Retail information technology,"$637,959","$59,248",1556000,United States,NaN,[5],NaN
2,3,State Grid Corporation of China,Electricity,"$545,948","$9,204",1361423,China,NaN,[6],NaN
3,4,Saudi Aramco,Oil and gas,"$480,446","$106,246",73311,Saudi Arabia,NaN,[7],NaN
4,5,China National Petroleum Corporation,Oil and gas,"$476,000","$25,250",1026301,China,NaN,[8],NaN

In [77]:
company_data.drop(columns=['Ref.'], axis=1, inplace=True)

In [78]:
company_data.head()

,Ranks,Name,Industry,Revenue,Profit,Employees,Headquarters[note 1],State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,"$680,985","$19,436",2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,"$637,959","$59,248",1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,"$545,948","$9,204",1361423,China,NaN,NaN
3,4,Saudi Aramco,Oil and gas,"$480,446","$106,246",73311,Saudi Arabia,NaN,NaN
4,5,China National Petroleum Corporation,Oil and gas,"$476,000","$25,250",1026301,China,NaN,NaN

## here we were able to get rid of the excess columns headers


- we removed the colmns we didnt need, the intituition is that we didn't need the ref column
- we showed what happens when you use the drop function.
- we used inplace as true to ensure that the ref column was deleted
- we used the axis parameter, by default it's 0 and 0 stands for rolls, so we used 1 which stands for columns

### Renaming column label

In [79]:
company_data.columns

Index(['Ranks', 'Name', 'Industry', 'Revenue', 'Profit', 'Employees',
       'Headquarters[note 1]', 'State-owned', 'Unnamed: 9_level_0'],
      dtype='object')

In [80]:
## remaning the columns
company_data.rename(columns=
                    {"Rank": "Ranking", 
                     "Name": "Company Name", 
                     "Headquarters[note 1]": "Headquaters"
                     }, inplace=True)

In [81]:
company_data.head(3)

,Ranks,Company Name,Industry,Revenue,Profit,Employees,Headquaters,State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,"$680,985","$19,436",2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,"$637,959","$59,248",1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,"$545,948","$9,204",1361423,China,NaN,NaN

In [82]:
## summary of the data
company_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ranks               51 non-null     int64
 1   Company Name        51 non-null     object
 2   Industry            51 non-null     object
 3   Revenue             51 non-null     object
 4   Profit              51 non-null     object
 5   Employees           51 non-null     int64
 6   Headquaters         51 non-null     object
 7   State-owned         0 non-null      float64
 8   Unnamed: 9_level_0  0 non-null      float64
dtypes: float64(2), int64(2), object(5)
memory usage: 3.7+ KB

In [83]:
# Take a closer look at the Rev colum
company_data['Revenue'].head(2)

0    $680,985
1    $637,959
Name: Revenue, dtype: object

In [84]:
# Remove the $ sign from the revenue column
company_data['Revenue'] = company_data['Revenue'].str.replace('$','')

In [85]:
company_data.head(3)

,Ranks,Company Name,Industry,Revenue,Profit,Employees,Headquaters,State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,"680,985","$19,436",2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,"637,959","$59,248",1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,"545,948","$9,204",1361423,China,NaN,NaN

In [86]:
## concised data summary
company_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ranks               51 non-null     int64
 1   Company Name        51 non-null     object
 2   Industry            51 non-null     object
 3   Revenue             51 non-null     object
 4   Profit              51 non-null     object
 5   Employees           51 non-null     int64
 6   Headquaters         51 non-null     object
 7   State-owned         0 non-null      float64
 8   Unnamed: 9_level_0  0 non-null      float64
dtypes: float64(2), int64(2), object(5)
memory usage: 3.7+ KB

In [87]:
# Remove the $ sign from the profit column
company_data['Profit'] = company_data['Profit'].str.replace('$','')

In [88]:
company_data.head()

,Ranks,Company Name,Industry,Revenue,Profit,Employees,Headquaters,State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,"680,985","19,436",2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,"637,959","59,248",1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,"545,948","9,204",1361423,China,NaN,NaN
3,4,Saudi Aramco,Oil and gas,"480,446","106,246",73311,Saudi Arabia,NaN,NaN
4,5,China National Petroleum Corporation,Oil and gas,"476,000","25,250",1026301,China,NaN,NaN

In [89]:
# Remove the comma sign from the rev column
company_data['Profit'] = company_data['Profit'].str.replace(',','')

In [90]:
company_data.head()

,Ranks,Company Name,Industry,Revenue,Profit,Employees,Headquaters,State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,"680,985",19436,2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,"637,959",59248,1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,"545,948",9204,1361423,China,NaN,NaN
3,4,Saudi Aramco,Oil and gas,"480,446",106246,73311,Saudi Arabia,NaN,NaN
4,5,China National Petroleum Corporation,Oil and gas,"476,000",25250,1026301,China,NaN,NaN

In [91]:
# Remove the comma sign from the revenue column
company_data['Revenue'] = company_data['Revenue'].str.replace(',','')

In [92]:
company_data.head()

,Ranks,Company Name,Industry,Revenue,Profit,Employees,Headquaters,State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,680985,19436,2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,637959,59248,1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,545948,9204,1361423,China,NaN,NaN
3,4,Saudi Aramco,Oil and gas,480446,106246,73311,Saudi Arabia,NaN,NaN
4,5,China National Petroleum Corporation,Oil and gas,476000,25250,1026301,China,NaN,NaN

In [93]:
## remaning the columns  for rev and column
company_data.rename(columns=
                    {"Revenue": "Revenue($)", 
                     "Profit": "Profit($)", 
                 }, inplace=True)

In [94]:
company_data.head(3)

,Ranks,Company Name,Industry,Revenue($),Profit($),Employees,Headquaters,State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,680985,19436,2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,637959,59248,1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,545948,9204,1361423,China,NaN,NaN

In [95]:
company_data.columns

Index(['Ranks', 'Company Name', 'Industry', 'Revenue($)', 'Profit($)',
       'Employees', 'Headquaters', 'State-owned', 'Unnamed: 9_level_0'],
      dtype='object')

In [96]:
company_data.dtypes

Ranks                   int64
Company Name           object
Industry               object
Revenue($)             object
Profit($)              object
Employees               int64
Headquaters            object
State-owned           float64
Unnamed: 9_level_0    float64
dtype: object

In [97]:
company_data['Revenue($)'].unique()

array(['680985', '637959', '545948', '480446', '476000', '429700',
       '400278', '391035', '371433', '357776', '350018', '348408',
       '344582', '331000', '323183', '320431', '312018', '308951',
       '281700', '262173', '244280', '242290', '239425', '222484',
       '218945', '217829', '213032', '205012', '204908', '200949',
       '199826', '198257', '197876', '195265', '192398', '180576',
       '178563', '177000', '176191', '172328', '171912', '171842',
       '171340', '168103', '165638', '164500', '160847', '157216',
       '156820', '155500', '147100'], dtype=object)

In [98]:
company_data['Profit($)'].unique()

array(['19436', '59248', '9204', '106246', '25250', '9393', '14405',
       '93736', '88995', '8344', '100118', '17945', '36010', '13000',
       '19359', '4272', '34214', '3002', '101800', '1745', '7393', '6292',
       '49552', '51417', '21384', '4280', '15239', '261', '20103',
       '21369', '46990', '11082', '4563', '5164', '38049', '16988',
       '2152', '17641', '4347', '32758', '26515', '10127', '5987',
       '12205', '15417', '62360', '1701', '2494', '9228', '31910', '3400'],
      dtype=object)

In [99]:
# Remove the - sign from the profit column
company_data['Profit($)'] = company_data['Profit($)'].str.replace('-','')

In [100]:
company_data['Revenue($)'].unique()

array(['680985', '637959', '545948', '480446', '476000', '429700',
       '400278', '391035', '371433', '357776', '350018', '348408',
       '344582', '331000', '323183', '320431', '312018', '308951',
       '281700', '262173', '244280', '242290', '239425', '222484',
       '218945', '217829', '213032', '205012', '204908', '200949',
       '199826', '198257', '197876', '195265', '192398', '180576',
       '178563', '177000', '176191', '172328', '171912', '171842',
       '171340', '168103', '165638', '164500', '160847', '157216',
       '156820', '155500', '147100'], dtype=object)

In [101]:
company_data['Profit($)'].unique()

array(['19436', '59248', '9204', '106246', '25250', '9393', '14405',
       '93736', '88995', '8344', '100118', '17945', '36010', '13000',
       '19359', '4272', '34214', '3002', '101800', '1745', '7393', '6292',
       '49552', '51417', '21384', '4280', '15239', '261', '20103',
       '21369', '46990', '11082', '4563', '5164', '38049', '16988',
       '2152', '17641', '4347', '32758', '26515', '10127', '5987',
       '12205', '15417', '62360', '1701', '2494', '9228', '31910', '3400'],
      dtype=object)

In [102]:
company_data[['Revenue($)', 'Profit($)']] = company_data[['Revenue($)', 'Profit($)']].astype(float)
## convert values in these columns to floats

In [103]:
company_data.head()

,Ranks,Company Name,Industry,Revenue($),Profit($),Employees,Headquaters,State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,680985.0,19436.0,2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,637959.0,59248.0,1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,545948.0,9204.0,1361423,China,NaN,NaN
3,4,Saudi Aramco,Oil and gas,480446.0,106246.0,73311,Saudi Arabia,NaN,NaN
4,5,China National Petroleum Corporation,Oil and gas,476000.0,25250.0,1026301,China,NaN,NaN

In [104]:
company_data.dtypes

Ranks                   int64
Company Name           object
Industry               object
Revenue($)            float64
Profit($)             float64
Employees               int64
Headquaters            object
State-owned           float64
Unnamed: 9_level_0    float64
dtype: object

## summary

- we did a little cleaning
- we removed inconsistencies, dollar signs from revenue and profits
- we added the dollar signs again to make it look intuitive so when you look at it you know we're referencing the dollar
- we tried to convert data signs to floats and we noticed the dash signs so we removed it
- we converted to float
- we got the data from wikipidia then cleaned it and made it look like what we wanted

we're working with data, and we are trying to understand the type of data we're worrking on.

In [105]:
## summary of the data
company_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ranks               51 non-null     int64
 1   Company Name        51 non-null     object
 2   Industry            51 non-null     object
 3   Revenue($)          51 non-null     float64
 4   Profit($)           51 non-null     float64
 5   Employees           51 non-null     int64
 6   Headquaters         51 non-null     object
 7   State-owned         0 non-null      float64
 8   Unnamed: 9_level_0  0 non-null      float64
dtypes: float64(4), int64(2), object(3)
memory usage: 3.7+ KB

In [106]:
# take a closer look at rev column
company_data['Revenue($)'].head(2)

0    680985.0
1    637959.0
Name: Revenue($), dtype: float64

In [111]:
company_data.dtypes

Ranks                   int64
Company Name           object
Industry               object
Revenue($)            float64
Profit($)             float64
Employees               int64
Headquaters            object
State-owned           float64
Unnamed: 9_level_0    float64
dtype: object

## data wrangling & subsetting a dataframe

Data wrangling is a form of transforming data and when you're transforming data, you're transforming data from one type to another type

- Enriching the data
- Looking at the big picture
- Raw data pieced together to required format
- Taking better decisions around cleaning and structuring data
- making data come to live

noise in data is that aspect of the data that have little or nothing to do with our business case and our bottom lines

## data wrangling

In [148]:
### subset our data
company_data.head(10)

,Ranks,Company Name,Industry,Revenue($),Profit($),Employees,Headquaters,State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,680985.0,19436.0,2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,637959.0,59248.0,1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,545948.0,9204.0,1361423,China,NaN,NaN
3,4,Saudi Aramco,Oil and gas,480446.0,106246.0,73311,Saudi Arabia,NaN,NaN
4,5,China National Petroleum Corporation,Oil and gas,476000.0,25250.0,1026301,China,NaN,NaN
5,6,China Petrochemical Corporation,Oil and gas,429700.0,9393.0,513434,China,NaN,NaN
6,7,UnitedHealth Group,Healthcare,400278.0,14405.0,400000,United States,NaN,NaN
7,8,Apple,Information technology,391035.0,93736.0,164000,United States,NaN,NaN
8,9,Berkshire Hathaway,Financials,371433.0,88995.0,392400,United States,NaN,NaN
9,10,CVS Health,Healthcare,357776.0,8344.0,259500,United States,NaN,NaN

In [127]:
company_data.columns

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

Index(['Ranks', 'Company Name', 'Industry', 'Revenue($)', 'Profit($)',
       'Employees', 'Headquaters', 'State-owned', 'Unnamed: 9_level_0'],
      dtype='object')

In [131]:
## subset this data
data_subset = company_data.loc[[i for i in range(1, 21)],['Revenue($)', 'Profit($)']]

In [132]:
data_subset

   Revenue($)  Profit($)
1    637959.0    59248.0
2    545948.0     9204.0
3    480446.0   106246.0
4    476000.0    25250.0
5    429700.0     9393.0
6    400278.0    14405.0
7    391035.0    93736.0
8    371433.0    88995.0
9    357776.0     8344.0
10   350018.0   100118.0
11   348408.0    17945.0
12   344582.0    36010.0
13   331000.0    13000.0
14   323183.0    19359.0
15   320431.0     4272.0
16   312018.0    34214.0
17   308951.0     3002.0
18   281700.0   101800.0
19   262173.0     1745.0
20   244280.0     7393.0

## Summary statistics shows us the mean, the median,and it shows us basically the distribution of our data.

it summarizes the central tendency, dispersion and shape of a data.

In [133]:
## summary statistics 
data_subset.describe()

           Profit($)
count      20.000000
mean    37683.950000
std     38385.882892
min      1745.000000
25%      8989.000000
50%     18652.000000
75%     66684.750000
max    106246.000000

In [134]:
# flitering
company_data.head()

,Ranks,Company Name,Industry,Revenue($),Profit($),Employees,Headquaters,State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,680985.0,19436.0,2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,637959.0,59248.0,1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,545948.0,9204.0,1361423,China,NaN,NaN
3,4,Saudi Aramco,Oil and gas,480446.0,106246.0,73311,Saudi Arabia,NaN,NaN
4,5,China National Petroleum Corporation,Oil and gas,476000.0,25250.0,1026301,China,NaN,NaN

In [136]:
##| employee column
company_data['Employees'].max()

np.int64(2100000)

In [137]:
company_data['Employees'].min()

np.int64(1560)

In [141]:
emp_data = company_data[company_data['Employees'] >= 100000]

In [142]:
emp_data

,Ranks,Company Name,Industry,Revenue($),Profit($),Employees,Headquaters,State-owned,Unnamed: 9_level_0
0,1,Walmart,Retail,680985.0,19436.0,2100000,United States,NaN,NaN
1,2,Amazon,Retail information technology,637959.0,59248.0,1556000,United States,NaN,NaN
2,3,State Grid Corporation of China,Electricity,545948.0,9204.0,1361423,China,NaN,NaN
4,5,China National Petroleum Corporation,Oil and gas,476000.0,25250.0,1026301,China,NaN,NaN
5,6,China Petrochemical Corporation,Oil and gas,429700.0,9393.0,513434,China,NaN,NaN
6,7,UnitedHealth Group,Healthcare,400278.0,14405.0,400000,United States,NaN,NaN
7,8,Apple,Information technology,391035.0,93736.0,164000,United States,NaN,NaN
8,9,Berkshire Hathaway,Financials,371433.0,88995.0,392400,United States,NaN,NaN
9,10,CVS Health,Healthcare,357776.0,8344.0,259500,United States,NaN,NaN
10,11,Alphabet,Information technology,350018.0,100118.0,183323,United States,NaN,NaN
11,12,Volkswagen Group,Automotive,348408.0,17945.0,684025,Germany,NaN,NaN
14,15,Shell,Oil and gas,323183.0,19359.0,103000,United Kingdom,NaN,NaN
15,16,China State Construction Engineering,Construction,320431.0,4272.0,382894,China,NaN,NaN
16,17,Toyota,Automotive,312018.0,34214.0,380793,Japan,NaN,NaN
18,19,Microsoft,Information technology,281700.0,101800.0,228000,United States,NaN,NaN
21,22,Costco,Retail,242290.0,6292.0,316000,United States,NaN,NaN
22,23,JPMorgan Chase,Financials,239425.0,49552.0,309926,United States,NaN,NaN
23,24,Industrial and Commercial Bank of China,Financials,222484.0,51417.0,419252,China,NaN,NaN
24,25,TotalEnergies,Oil and gas,218945.0,21384.0,102579,France,NaN,NaN
28,29,Stellantis,Automotive,204908.0,20103.0,258275,Netherlands,NaN,NaN
30,31,China Construction Bank,Financials,199826.0,46990.0,376871,China,NaN,NaN
31,32,Samsung Electronics,Electronics,198257.0,11082.0,267860,South Korea,NaN,NaN
32,33,Foxconn,Electronics,197876.0,4563.0,621393,Taiwan,NaN,NaN
34,35,Agricultural Bank of China,Financials,192398.0,38049.0,451003,China,NaN,NaN
35,36,Schwarz Gruppe,Retail,180576.0,16988.0,595000,Germany,NaN,NaN
36,37,China Railway Engineering Corporation,Construction,178563.0,2152.0,314149,China,NaN,NaN
37,38,Cargill,Conglomerate,177000.0,17641.0,160000,United States,NaN,NaN
38,39,Ford Motor Company,Automotive,176191.0,4347.0,177000,United States,NaN,NaN
39,40,Bank of China,Financials,172328.0,32758.0,306931,China,NaN,NaN
40,41,Bank of America,Financials,171912.0,26515.0,212985,United States,NaN,NaN
41,42,General Motors,Automotive,171842.0,10127.0,163000,United States,NaN,NaN
42,43,Elevance Health,Healthcare,171340.0,5987.0,104900,United States,NaN,NaN
43,44,BMW Group,Automotive,168103.0,12205.0,154950,Germany,NaN,NaN
44,45,Mercedes-Benz Group,Automotive,165638.0,15417.0,166056,Germany,NaN,NaN
46,47,China Railway Construction Corporation,Construction,160847.0,1701.0,336433,China,NaN,NaN
47,48,Baowu,Steel,157216.0,2494.0,258697,China,NaN,NaN
48,49,Citigroup,Financials,156820.0,9228.0,237925,United States,NaN,NaN

In [143]:
emp_data = company_data[company_data['Employees'] <= 100000] 
#less than a million

In [144]:
emp_data

,Ranks,Company Name,Industry,Revenue($),Profit($),Employees,Headquaters,State-owned,Unnamed: 9_level_0
3,4,Saudi Aramco,Oil and gas,480446.0,106246.0,73311,Saudi Arabia,NaN,NaN
12,13,ExxonMobil,Oil and gas,344582.0,36010.0,61500,United States,NaN,NaN
13,14,Vitol,Commodities,331000.0,13000.0,1560,Switzerland,NaN,NaN
17,18,McKesson,Healthcare,308951.0,3002.0,48000,United States,NaN,NaN
19,20,Cencora,Healthcare,262173.0,1745.0,44000,United States,NaN,NaN
20,21,Trafigura,Commodities,244280.0,7393.0,12479,Singapore,NaN,NaN
25,26,Glencore,Commodities,217829.0,4280.0,83426,Switzerland,NaN,NaN
26,27,BP,Oil and gas,213032.0,15239.0,79400,United Kingdom,NaN,NaN
27,28,Cardinal Health,Healthcare,205012.0,261.0,47520,United States,NaN,NaN
29,30,Chevron,Oil and gas,200949.0,21369.0,45600,United States,NaN,NaN
33,34,Cigna,Healthcare,195265.0,5164.0,71413,United States,NaN,NaN
45,46,Meta Platforms,Social media,164500.0,62360.0,78450,United States,NaN,NaN
49,50,Nvidia,Semiconductors,155500.0,31910.0,36000,United States,NaN,NaN
50,51,Enel,Energy,147100.0,3400.0,61060,Italy,NaN,NaN

In [147]:
emp_data['Ranks'].min()

np.int64(4)